{% set name = "rdflib" %}
{% set version = "5.0.0" %}
{% set sha256 = "d3add5503970ddefc1cc49653af8d9689426f6ac0a025d4f9e8eced7ab7c851b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nipy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - isodate
    - pyparsing
    - html5lib
    - sparqlwrapper

test:
  imports:
    - rdflib
    - rdflib.extras
    - rdflib.plugins
    - rdflib.plugins.parsers
    - rdflib.plugins.parsers
    - rdflib.plugins.serializers
    - rdflib.plugins.sparql
    - rdflib.plugins.stores
    - rdflib.tools

  commands:
    - rdfpipe --help
    - rdfgraphisomorphism --help

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.'
  dev_url: https://github.com/RDFLib/rdflib
  doc_url: https://rdflib.readthedocs.io

extra:
  recipe-maintainers:
    - satra
