{% set name = "rdflib" %}
{% set version = "7.1.4" %}

package:
  name: {{ name }}-packages
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fed46e24f26a788e2ab8e445f7077f00edcf95abb73bcef4b86cefa8b62dd174

build:
  number: 0
  skip: True  # [py<38]
  requirements:
    host:
      - python
    run:
      - python

outputs:
  - name: rdflib
    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]
    entry_points:
      - rdfpipe = rdflib.tools.rdfpipe:main
      - csv2rdf = rdflib.tools.csv2rdf:main
      - rdf2dot = rdflib.tools.rdf2dot:main
      - rdfs2dot = rdflib.tools.rdfs2dot:main
      - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main
    requirements:
      host:
        - python
        - pip
        - poetry-core >=2.0.0
      run:
        - python
        # Drop upstream python limitation for isodate
        # Due to failing import tests
        - isodate >=0.7.0,<1.0.0
        - pyparsing >=3.2.0,<4
      run_constrained:
        - berkeleydb >=18.1.0,<19
        - networkx >=2,<4
        - html5rdf >=1.2,<2
        - lxml >=4.3,<6.0
        - orjson >=3.9.14,<4
    test:
      source_files:
        - test
        - examples
        - rdflib/tools
      requires:
        - pip
        - pytest >=7.1.3,<9.0.0
        - pytest-cov >=4,<7
      imports:
        - rdflib
        - rdflib._networking
        - rdflib.collection
        - rdflib.compare
        - rdflib.compat
        - rdflib.container
        - rdflib.events
        - rdflib.exceptions
        - rdflib.extras.cmdlineutils
        - rdflib.extras.infixowl
        - rdflib.extras.shacl
        - rdflib.graph
        - rdflib.namespace
        - rdflib.parser
        - rdflib.paths
        - rdflib.plugin
        - rdflib.plugins
        - rdflib.query
        - rdflib.resource
        - rdflib.serializer
        - rdflib.store
        - rdflib.term
        - rdflib.tools
        - rdflib.tools.chunk_serializer
        - rdflib.tools.defined_namespace_creator
        - rdflib.util
        - rdflib.xsd_datetime
        - rdflib.plugins
      commands:
        - pip check
        - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
        # test_guess_format_for_parse_http_text_plain-> urllib.error.HTTPError: HTTP Error 406: Not Acceptable
        - pytest -k "not test_guess_format_for_parse_http_text_plain" test
        - rdfgraphisomorphism --help
        - rdfpipe --help
        # Following scripts 'help' option exit program as error
        - rdfs2dot -h || true
        - rdf2dot -h || true
        - csv2rdf --help || true

  - name: rdflib-with-networkx
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("rdflib", exact=True) }}
        - networkx >=2,<4
    test:
      imports:
        - rdflib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from rdflib.extras.external_graph_libs import rdflib_to_networkx_graph; import rdflib; assert rdflib_to_networkx_graph(rdflib.Graph()) is not None"

  - name: rdflib-with-lxml
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("rdflib", exact=True) }}
        - lxml >=4.3,<6.0
    test:
      imports:
        - rdflib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from rdflib.plugins.sparql.results import xmlresults; assert xmlresults.lxml_etree"

  - name: rdflib-with-orjson
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("rdflib", exact=True) }}
        - orjson >=3.9.14,<4
    test:
      imports:
        - rdflib
      requires:
        - pip
      commands:
        - pip check
        - python -c "from rdflib.plugins.sparql.results import jsonresults; assert jsonresults.orjson"
          
  - name: rdflib-with-all
    requirements:
      host:
        - python
      run:
        - python
        # html5rdf is not in channels
        # - {{ pin_subpackage("rdflib-with-html", exact=True) }}
        - {{ pin_subpackage("rdflib-with-lxml", exact=True) }}
        - {{ pin_subpackage("rdflib-with-networkx", exact=True) }}
        - {{ pin_subpackage("rdflib-with-orjson", exact=True) }}
        - {{ pin_subpackage("rdflib", exact=True) }}
    test:
      imports:
        - rdflib
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/RDFLib/rdflib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: RDFLib is a Python library for working with RDF, a simple yet powerful language for representing information.
  dev_url: https://github.com/RDFLib/rdflib
  doc_url: https://rdflib.readthedocs.io
  description: RDFLib is a pure Python package for working with RDF. RDFLib contains most things you need to work with RDF, including 
    parsers and serializers for RDF/XML, N3, NTriples, N-Quads, Turtle, TriX, Trig and JSON-LD
    a Graph interface which can be backed by any one of a number of Store implementations
    store implementations for in-memory, persistent on disk (Berkeley DB) and remote SPARQL endpoints
    a SPARQL 1.1 implementation - supporting SPARQL 1.1 Queries and Update statements
    SPARQL function extension mechanisms

extra:
  recipe-maintainers:
    - satra
    - nicholascar
    - bollwyvl
