# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Zb15xWOdmdtqWjHmFcgtEKqykwPVigzO7hGKxrtMJ+yl2AHEvW7rduBFRichHHKfD8FTkLHpJv5ZoyXNkCrtGARvaabUHFrAyub7Aq9h+sop2blDteEa/4hi+FMo/l5zPAbJla0abyg19lXercTPzQSODwoiP5mr0iV8l5AiL4OILBK+pOtZ6U8h1ei1oy7nZRDcGE9+hs/yoX2tMzOfkl9b3qNSuvfeqxhjGkCa7aMozev9Bc1Y9JPYf21axVEne4qD51CddBLKRMOz+olDO8X58es+dXpuuNguDVH+p2CYH+tH+yXHHL+F00GDeZy4nq+VP2rJiE0oMc9zJACy0KN/GIxd4B1/MhDeJT79Dvho7UiI36Pf5mHOYlw7Q6oC3w9RtP9NwV9lS8VAvGfd1ZQ9hSzLoR81aTrrnQOJhmYoCw5Vp92QCEI/J0MVT+NgAgNs4ElU/0ervbeHw9WTfapcgUQrt9ZGUGdVYi8BOW1gYisKwiYomzQUOqSnZf6H8MGadDZ4bbFSvUtstuN/TH9CW8+vKjeXjI2/uyfmD4k/bMeECb+OSz9qupU2aaHdL+dD+HHG+2DpESoCBFjkzxoVrVtAX3glbrMarPm+WGaWGxKtueYm+fv6cyDuSwikp82F1mK9NmID8AohmGUYO7IYt40C6vybMv6ShZaGuwI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
