travis:
  secure:
    BINSTAR_TOKEN: iGEMjkT35CfclMthEpQnLUj6QWa4qjaqrtyAfj6aXunYIRtALJEPGChTQYCd7ymyMbH1zsgfEBIva2hTlkZtwGet4h2sRQck4YmB8mQFJ58Ri9+gmRLetm82v6e1yEIispDBCHZvCWL99EgeT/Xn5zPruEdVRrUINSJyXIw/SxEhzwP5kpKVc01hlXHkKVM0WfuFe/+LsBOSdzCUfqeoPTJlWXJVQukA7EUZsKfA0fn79UAZaBh+BwUoCWQMWLQXNmSeGgUEm3y91YTDH52uuehE7WJ5+vvl4dj+j/sSNF9Xji3UGcZaLpxshFlfwePy3ez+91d93vnhp298PYITIHUHH+nXQJ800j1LWVg2fwSUBLE7Oe0vtYTFQMXSr/Kv6bLPlg2jkC0+8SH3nArvHdBKRt4zMWcyacoi1JgF8LknhSiexjccmL9CGgFLWeFd7EzgXusCY//z1OqgamJpkIfN+sitPIlJqT/sGNAi/9UqWvIwrTRxrrOHpf9kglSksX1zxG7FfzBYkWAUp1oh/UAFvZU2OdyUjXQq7oE04w0C0ZTFC8KCuhpK2x4zGRz64yCtnGvUzQirSAcoVWOZhhoa39GaCwirkr1r5a/NnCdKpeUxqmlT3ZpxnsQWhnzhlI4QJPKPr/HhTi6bNccUj8KbC4Teqn3MCILK5SW50xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
